### ISSUE TITLE
모듈 이미지가 정상적으로 표시되지 않습니다

### ISSUE THREAD

**Issue by dalverlic** [siege-green/onyx-issues#9]
https://i.imgur.com/ISK2ZIQ.png

건이 eft에선 잘 끌려오고 다른 모든 모듈은 다 순서대로 이쁘게 보이는데 건만 보이지 않습니다.

**Comment by meloncafe** [comment]
meloncafe/eve-onyx-django@1be3ac44c5b0c94504a700bf8fede6a3a3e1174b
High 모듈에 탄약이 포함되어 있을경우 정상적으로 표시되도록 수정
